# Site Configuration
site_name: AI Innovations Hub
logo: /2.jpg
tagline: Pushing the Boundaries of Artificial Intelligence

# Theme Settings
theme: jekyll-theme-cayman
color_scheme: dark

# Author Details
author:
  name: Dr. Subramanyam Sahoo
  role: Senior AI Researcher
  bio: >
    Specializing in neural networks and reinforcement learning,
    with a focus on developing AI solutions for real-world problems.

# Social Media and Contact
social:
  github: Subramanyam-Sahoo
  twitter: SubramanyamAI
  linkedin: subramanyam-sahoo-ai
  email: contact@subramanyamsahoo.ai

# Navigation
header_pages:
  - research.md
  - publications.md
  - projects.md
  - blog.md

# Content Settings
show_excerpts: true
permalink: /:categories/:year/:month/:day/:title:output_ext

# SEO and Analytics
google_analytics: UA-XXXXXXXXX-X
seo:
  name: Dr. Subramanyam Sahoo - AI Researcher
  type: Person

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
